version: '3.7'

networks:
  newsletter-network:

# docker-compose.yml
# Add this top-level entry
services:
  dynamodb-mediktiv:
    image: amazon/dynamodb-local
    container_name: dynamodb-mediktiv
    networks:
      - newsletter-network

  wrapper-notification:
    image: 027943877338.dkr.ecr.eu-west-1.amazonaws.com/mediktiv/wrapper-notification:build-${WRAPPER_COMMIT}
    container_name: wrapper-notification
    environment:
      AWS_ACCESS_KEY_ID: 'dummy'
      AWS_SECRET_ACCESS_KEY: 'dummy'
      AWS_DEFAULT_REGION: 'eu-west-1'
      ENVIRONMENT: 'local'
      KINESIS_STREAM_ENDPOINT: 'http://kinesis-streams-mediktiv:4567'
      KINESIS_STREAM_NAME: 'wrapper-notification'
      DYNAMO_ENDPOINT: 'http://dynamodb-mediktiv:8000'
      DYNAMO_TABLE: 'notification'
      CLEAN_DATA_SERVICES: 'true'
      LOG_SERVICE_NAME: 'wrapper-notification'
      LOG_LEVEL: DEBUG
      WRAPPER_HOST: '0.0.0.0:50059'
      DYNAMO_TABLE_CONFIG: 'mediktiv-dev-notification.json'
    ports:
      - '50060:50059'
    depends_on:
      - dynamodb-mediktiv
      - kinesis-stream-mediktiv
    networks:
      - mediktiv-microservices

  redis:
    image: redis
    container_name: cache
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
    networks:
      - newsletter-microservices


